### ISSUE TITLE
VOD schema

### ISSUE THREAD

**Issue by charlespalmer106** [jdpurcell/RechatTool#11]
Not an issue, but I was wondering if there is documentation for the VOD json scheme? I'm trying to figure out things like 'message.is_action' and 'message.user_notice_params.msg-param-threshold'. Any assistance would be appreciated.

**Comment by jdpurcell** [comment]
The .json file saved by RechatTool is basically the raw message data received back from the Twitch servers. so I don't know what all of it means. I do happen to know that "is_action" is true if someone types something with the "/me" command in the chat. As for msg-param-threshold I found it mentioned on this page: https://dev.twitch.tv/docs/irc/tags

**Comment by charlespalmer106** [comment]
Thanks so much. I had found the irc/tag but was hoping Twitch had a full description of the variables.
I've been using your tool for the past year on a research project. My work would not be possible without RechatTool.

Thanks
