### ISSUE TITLE
404/410 powershell error

### ISSUE THREAD

**Issue by gillo21** [jdpurcell/RechatTool#13]
I was cleaning my disk and noticed a 410 error popup on my powershell. Recently I got a 404 error. Is there an alternative that I can still use twitch rechat tool?

![Screenshot 2022-12-24 005701](https://user-images.githubusercontent.com/121308288/209369696-09cf6cad-283c-451d-be52-f99490c0d92e.jpg)

**Comment by jdpurcell** [comment]
Make sure you're using the [latest version](https://github.com/jdpurcell/RechatTool/releases), currently 2.0.0. The older versions no longer work due changes made by Twitch.
