### ISSUE TITLE
Error: Cannot access child value on Newtonsoft.Json.Linq.JValue.

### ISSUE THREAD

**Issue by MrNgL** [jdpurcell/RechatTool#14]
Hi there! First of all, I'd like to thank the author for creating RechatTool – it's been really helpful. However, I've recently encountered an error while using version 2.0.0 that I can't seem to resolve.

When trying to download a chat log from a Twitch VOD using the command "RechatTool.exe -D <VOD_ID>", I get the following error message: "Error: Cannot access child value on Newtonsoft.Json.Linq.JValue."

I've tried running the command with different VOD IDs, but the error persists. Is it just me or twitch changed their endpoint or JSON structure?

Thanks in advance for any help!

**Comment by jdpurcell** [comment]
Thanks for reporting. It seems Twitch is adding more validation to make it harder for 3rd parties to access their API. RechatTool 2.1.0 has been released which fixes this issue, thanks to a workaround found by another program's author as discussed in [this issue](https://github.com/lay295/TwitchDownloader/issues/704#issuecomment-1535595293). Not sure how long this will work before Twitch potentially blocks it as well, we'll see.
