### ISSUE TITLE
Special Request

### ISSUE THREAD

**Issue by AndrasRichter** [jdpurcell/RechatTool#5]
Hello J.D Purcell :) .

Unfortunately I have to contact you here via Github, there are no other contact information.

I would like to ask you whether it would be possible to develop a software tool that reads the bookmarks from an Android smartphone using a .Hmtl file so that they can then be exported and opened on the PC?

Please, for an answer, see my E-Mail Adress.

**Comment by daversls** [comment]
+1 but for obs replay
