### ISSUE TITLE
Newtonsoft.Json is not found

### ISSUE THREAD

**Issue by G3catcher** [jdpurcell/RechatTool#7]
On 1.5.6, the download executes, but is not completed on this specific file due to another error that I believe you fixed in 1.5.7.
On 1.5.7, I get this error when trying to download any file. I am only using the -D command.
![error](https://user-images.githubusercontent.com/55508592/104970743-8419bb00-59ba-11eb-8b7e-c9e088b0cdb4.PNG)

**Comment by jdpurcell** [comment]
@G3catcher Oops, yeah the zip contained the wrong Newtonsoft.Json file. You can download the release again as it contains the correct file now.
